# Generated by Django 3.0.7 on 2020-11-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_auto_20201127_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=255)),
                ('colours', models.CharField(max_length=255)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.Item')),
            ],
        ),
    ]
