# Generated by Django 3.0.7 on 2020-11-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.Item'),
        ),
    ]
