# Generated by Django 3.0.7 on 2020-11-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_auto_20201127_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.Item'),
        ),
    ]
