# Generated by Django 3.0.7 on 2020-11-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_auto_20201127_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True)),
                ('accepted_status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'IDLE'), (3, 'REPAIR')], default=2),
        ),
    ]
