# Generated by Django 3.0.7 on 2020-11-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_auto_20201129_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstatus',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.District'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'IDLE'), (3, 'REPAIR')], default=2),
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='ItemStatus',
        ),
    ]
