# Generated by Django 3.0.7 on 2020-11-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0012_auto_20201129_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.District')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.Item')),
            ],
        ),
    ]
