# Generated by Django 3.0.7 on 2020-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0013_reallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='process',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'IN PROCESS')], default=1),
        ),
    ]
