# Generated by Django 3.0.7 on 2020-11-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_auto_20201130_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
