# Generated by Django 3.0.7 on 2020-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0017_item_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
