# Generated by Django 3.0.7 on 2020-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0020_auto_20201204_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminfo',
            old_name='current_value',
            new_name='depreciation',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
