# Generated by Django 3.0.7 on 2020-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0021_auto_20201204_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
