# Generated by Django 3.0.7 on 2020-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0023_auto_20201205_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'MSEGS'), (2, 'SUPPLIER'), (3, 'DISTRICT')], default=3),
        ),
    ]
